services:
  flex-text-gen:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    volumes:
      - ./config.yaml:/app/config.yaml
    # environment:
    #   - USER_UID=1000
    #   - USER_GID=1000

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/.ollama:/root/.ollama
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]